// Generated by Wrangler on Fri Sep 13 2024 18:03:02 GMT-0500 (Central Daylight Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	COUNTER: DurableObjectNamespace<import("./src/index").Counter>;
	LIMITER: DurableObjectNamespace<import("./src/index").Limiter>;
}
